#include "ui_macros.h"

class Bridge_Dialog {
    idd = BRIDGE_DIALOG_IDD;
    controlsBackground[] = {};
    objects[] = {};
    onLoad = "[] spawn bridge_menu_fnc_open;";
    onUnload = "[] call bridge_menu_fnc_close;";

    #include "base_controls.h"

    class MenuButton : RscButton {
        colorBackground[] = NO_COLOR;
        colorFocused[] = NO_COLOR;
        x = MENU_BUTTON_X(0);
        y = MENU_BUTTON_Y(0);
        w = MENU_BUTTON_W;
        h = MENU_BUTTON_H;
        text = "";
    };

    class DebugConsoleSnippetButton : RscButton {
        w = DEBUG_CONSOLE_SNIPPET_BUTTON_W;
        h = DEBUG_CONSOLE_SNIPPET_BUTTON_H;
    };
//--------------------------
    class controls {
        class DialogBackground : RscBase {
            idc = BRIDGE_DIALOG_BACKGROUND_IDC;
            x = DIALOG_X;
            y = DIALOG_Y;
            h = DIALOG_H;
            w = DIALOG_W;
            colorBackground[] = DIALOG_BG_COLOR;
            colorText[] = NO_COLOR;
        };
//--------------------------
        MENU_BUTTON(0,BRIDGE_MENU_BUTTON0_IDC,0,0);
        MENU_BUTTON(1,BRIDGE_MENU_BUTTON1_IDC,0,1);
        MENU_BUTTON(2,BRIDGE_MENU_BUTTON2_IDC,0,2);
        MENU_BUTTON(3,BRIDGE_MENU_BUTTON3_IDC,0,3);
        MENU_BUTTON(4,BRIDGE_MENU_BUTTON4_IDC,1,0);
        MENU_BUTTON(5,BRIDGE_MENU_BUTTON5_IDC,1,1);
        MENU_BUTTON(6,BRIDGE_MENU_BUTTON6_IDC,1,2);
        MENU_BUTTON(7,BRIDGE_MENU_BUTTON7_IDC,1,3);
        MENU_BUTTON(8,BRIDGE_MENU_BUTTON8_IDC,2,0);
        MENU_BUTTON(9,BRIDGE_MENU_BUTTON9_IDC,2,1);
        MENU_BUTTON(10,BRIDGE_MENU_BUTTON10_IDC,2,2);
        MENU_BUTTON(11,BRIDGE_MENU_BUTTON11_IDC,2,3);
        MENU_BUTTON(12,BRIDGE_MENU_BUTTON12_IDC,3,0);
        MENU_BUTTON(13,BRIDGE_MENU_BUTTON13_IDC,3,1);
        MENU_BUTTON(14,BRIDGE_MENU_BUTTON14_IDC,3,2);
        MENU_BUTTON(15,BRIDGE_MENU_BUTTON15_IDC,3,3);
        MENU_BUTTON(16,BRIDGE_MENU_BUTTON16_IDC,4,0);
        MENU_BUTTON(17,BRIDGE_MENU_BUTTON17_IDC,4,1);
        MENU_BUTTON(18,BRIDGE_MENU_BUTTON18_IDC,4,2);
        MENU_BUTTON(19,BRIDGE_MENU_BUTTON19_IDC,4,3);
//--------------------------
        class Map: RscMapControl {
            idc = BRIDGE_MAP_IDC;
            x = MAP_X;
            y = MAP_Y;
            w = MAP_W;
            h = MAP_H;
            onMouseButtonDown = "";
            onDraw = "";
        };
//--------------------------
        class DebugConsoleEditor : RscEditor {
            idc = BRIDGE_DEBUG_CONSOLE_EDITOR_IDC;
            style = ST_MULTI;
            x = CONTENT_BASE_X;
            y = DEBUG_CONSOLE_EDITOR_Y;
            w = DEBUG_CONSOLE_EDITOR_W;
            h = DEBUG_CONSOLE_EDITOR_H;
        };

        class DebugConsoleSnippetTooltip : RscEditor {
            idc = BRIDGE_DEBUG_CONSOLE_SNIPPET_TOOLTIP_IDC;
            x = DEBUG_CONSOLE_EDITOR_EXECUTE_BUTTON_X;
            y = DEBUG_CONSOLE_SNIPPET_TOOLTIP_Y;
            w = DEBUG_CONSOLE_EDITOR_EXECUTE_BUTTON_W;
            h = DEBUG_CONSOLE_SNIPPET_TOOLTIP_H;
            tooltip = "Snippet tooltip";
        };

        DEBUG_CONSOLE_SNIPPET_BUTTON(0, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON0_IDC ,0,0,"#1");
        DEBUG_CONSOLE_SNIPPET_BUTTON(1, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON1_IDC ,0,1,"#2");
        DEBUG_CONSOLE_SNIPPET_BUTTON(2, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON2_IDC ,0,2,"#3");
        DEBUG_CONSOLE_SNIPPET_BUTTON(3, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON3_IDC ,0,3,"#4");
        DEBUG_CONSOLE_SNIPPET_BUTTON(4, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON4_IDC ,1,0,"#5");
        DEBUG_CONSOLE_SNIPPET_BUTTON(5, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON5_IDC ,1,1,"#6");
        DEBUG_CONSOLE_SNIPPET_BUTTON(6, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON6_IDC ,1,2,"#7");
        DEBUG_CONSOLE_SNIPPET_BUTTON(7, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON7_IDC ,1,3,"#8");
        DEBUG_CONSOLE_SNIPPET_BUTTON(8, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON8_IDC ,2,0,"#9");
        DEBUG_CONSOLE_SNIPPET_BUTTON(9, BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON9_IDC ,2,1,"#10");
        DEBUG_CONSOLE_SNIPPET_BUTTON(10,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON10_IDC,2,2,"#11");
        DEBUG_CONSOLE_SNIPPET_BUTTON(11,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON11_IDC,2,3,"#12");
        DEBUG_CONSOLE_SNIPPET_BUTTON(12,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON12_IDC,3,0,"#13");
        DEBUG_CONSOLE_SNIPPET_BUTTON(13,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON13_IDC,3,1,"#14");
        DEBUG_CONSOLE_SNIPPET_BUTTON(14,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON14_IDC,3,2,"#15");
        DEBUG_CONSOLE_SNIPPET_BUTTON(15,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON15_IDC,3,3,"#16");
        DEBUG_CONSOLE_SNIPPET_BUTTON(16,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON16_IDC,4,0,"#17");
        DEBUG_CONSOLE_SNIPPET_BUTTON(17,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON17_IDC,4,1,"#18");
        DEBUG_CONSOLE_SNIPPET_BUTTON(18,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON18_IDC,4,2,"#19");
        DEBUG_CONSOLE_SNIPPET_BUTTON(19,BRIDGE_DEBUG_CONSOLE_SNIPPET_BUTTON19_IDC,4,3,"#20");

        class DebugConsoleEditorContextCombo : RscCombo {
            idc = BRIDGE_DEBUG_CONSOLE_EDITOR_CONTEXT_COMBO_IDC;
            x = DEBUG_CONSOLE_EDITOR_CONTEXT_COMBO_X;
            y = DEBUG_CONSOLE_EDITOR_CONTEXT_COMBO_Y;
            w = DEBUG_CONSOLE_EDITOR_CONTEXT_COMBO_W;
            h = DEBUG_CONSOLE_EDITOR_CONTEXT_COMBO_H;
            onLBSelChanged = "_this call bridge_console_fnc_executeContextChanged";
        };

        class DebugConsoleEditorExecuteButton : RscButton {
            idc = BRIDGE_DEBUG_CONSOLE_EDITOR_EXECUTE_BUTTON_IDC;
            x = DEBUG_CONSOLE_EDITOR_EXECUTE_BUTTON_X;
            y = DEBUG_CONSOLE_EDITOR_EXECUTE_BUTTON_Y;
            w = DEBUG_CONSOLE_EDITOR_EXECUTE_BUTTON_W;
            h = DEBUG_CONSOLE_EDITOR_EXECUTE_BUTTON_H;
            text = "Execute";
            onButtonClick = "[] call bridge_console_fnc_executeClicked";
        };
//--------------------------
        DEBUG_CONSOLE_WATCH(0,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR0_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT0_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT0_IDC);
        DEBUG_CONSOLE_WATCH(1,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR1_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT1_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT1_IDC);
        DEBUG_CONSOLE_WATCH(2,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR2_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT2_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT2_IDC);
        DEBUG_CONSOLE_WATCH(3,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR3_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT3_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT3_IDC);
        DEBUG_CONSOLE_WATCH(4,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR4_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT4_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT4_IDC);
        DEBUG_CONSOLE_WATCH(5,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR5_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT5_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT5_IDC);
        DEBUG_CONSOLE_WATCH(6,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR6_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT6_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT6_IDC);
        DEBUG_CONSOLE_WATCH(7,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR7_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT7_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT7_IDC);
        DEBUG_CONSOLE_WATCH(8,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR8_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT8_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT8_IDC);
        DEBUG_CONSOLE_WATCH(9,BRIDGE_DEBUG_CONSOLE_WATCH_EDITOR9_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_CONTENXT9_IDC,BRIDGE_DEBUG_CONSOLE_WATCH_RESULT9_IDC);
    };
};
